#!/usr/bin/env bash

RG_PREFIX="${RG_PREFIX:-"rga --files-with-matches --smart-case"} $@"
#FZF_DEFAULT_COMMAND=$RG_PREFIX \
    fzf --sort --preview="[[ ! -z {} ]] && rga --line-number --pretty --context 5 {q} {}" \
        --phony \
        --bind "change:reload:$RG_PREFIX {q}" \
        --preview-window="70%:wrap"

